### ISSUE TITLE
#US05 - Creación y gestión de eventos

### ISSUE THREAD

**Issue by wesborland-github** [Full-Juan-Ortega/VotoElectronicoAndroid#30]
>"Como usuario autenticado, quiero tener la capacidad de crear eventos desde una actividad específica en la aplicación. Debo poder proporcionar detalles sobre el evento, como título, descripción, puntuación."
___
## <strong>Descripción</strong>
___
El usuario debe poder crear un evento con los datos de "titulo, puntuacion, descripcion".
___
## <strong>Criterios de aceptación</strong>
___
La aplicación debe ofrecer una activity para crear un evento con los datos de "titulo, puntuacion, descripcion".

**Comment by Full-Juan-Ortega** [comment]
Evento creado
