### ISSUE TITLE
#US06 - Gestión de eventos

### ISSUE THREAD

**Issue by wesborland-github** [Full-Juan-Ortega/VotoElectronicoAndroid#31]
>"Como usuario autenticado, quiero ver un historial de los eventos que he creado en una actividad. Desde este historial, debo tener la opción de editar y eliminar los eventos según sea necesario."
___
## <strong>Descripción</strong>
___
El usuario debe poder acceder al historial en la aplicación desde el cual pueda realizar ediciones y eliminar según lo necesite.
___
## <strong>Criterios de aceptación</strong>
___
La aplicación debe ofrecer un historial con los eventos creados desde el cual se pueda editar o eliminar cualquier evento disponible.

**Comment by Full-Juan-Ortega** [comment]
Listo el historial de votaciones
