### ISSUE TITLE
#TK18 - Agregar Auth0 para el inicio de sesión

### ISSUE THREAD

**Issue by wesborland-github** [Full-Juan-Ortega/VotoElectronicoAndroid#50]
Se debe implementar la funcionalidad de inicio de sesión de usuarios utilizando Auth0. Se requiere configurar Auth0 en el proyecto para permitir a los usuarios autenticarse con sus credenciales y utilizarlo como proveedor de autenticación en la aplicación.

**Comment by Full-Juan-Ortega** [comment]
Implementada como auth0service
