### ISSUE TITLE
#TK19 - Agregar dependencias de Auth0 a Gradle

### ISSUE THREAD

**Issue by wesborland-github** [Full-Juan-Ortega/VotoElectronicoAndroid#51]
Se deben agregar las dependencias necesarias de Auth0 al archivo Gradle para que la autenticación funcione correctamente. Con esto lograremos que el proyecto pueda comunicarse adecuadamente con los servicios de Auth0.

**Comment by Full-Juan-Ortega** [comment]
Dependencia auth0 lista en gradle
