### ISSUE TITLE
#TK20 - Configurar las variables de entorno de Auth0 (redirección)

### ISSUE THREAD

**Issue by wesborland-github** [Full-Juan-Ortega/VotoElectronicoAndroid#52]
Se deben configurar las variables de Auth0, como la URL de redirección, para que la autenticación funcione correctamente. Esto  permitirá que la aplicación redirija a los usuarios a la pantalla principal después de un inicio de sesión correcto.

**Comment by Full-Juan-Ortega** [comment]
Redirección lista a la pantalla principal una ves logueado
