### ISSUE TITLE
#TK22 - Crear alert de confirmación para cambios

### ISSUE THREAD

**Issue by wesborland-github** [Full-Juan-Ortega/VotoElectronicoAndroid#54]
Se debe implementar la funcionalidad de alerts de confirmación que se utilizarán para solicitar al usuario que confirme si está seguro de realizar cambios en la aplicación. Estos modales deberán aparecer antes de realizar cambios como eliminar, editar o crear información. El alert deberá tener opciones de "Aceptar" y "Cancelar". Si el usuario selecciona "Aceptar", se realizarán los cambios solicitados; de lo contrario, los cambios no se llevarán a cabo.

**Comment by Full-Juan-Ortega** [comment]
Implementados los alert de confirmación
